public enum DamageSource
{
    DAMAGE_SOURCE_RAW,
    DAMAGE_SOURCE_INTERNALRAW,
    DAMAGE_SOURCE_PERIODIC,
    DAMAGE_SOURCE_PROC,
    DAMAGE_SOURCE_REACTIVE,
    DAMAGE_SOURCE_ONDEATH,
    DAMAGE_SOURCE_SPELL,
    DAMAGE_SOURCE_ATTACK,
    DAMAGE_SOURCE_DEFAULT,
    DAMAGE_SOURCE_SPELLAOE,
    DAMAGE_SOURCE_SPELLPERSIST,
    DAMAGE_SOURCE_PET
}